---
title: "Lecture 3"
author: "Joe Roith"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  pdf_document: default
  html_document: default
---


### Time/Location

Thursdays: 12:45 - 2:05 PM (80 min)

RNS 210

### Previous class

Finished talking about the 7 components of statistical sleuthing articles. They have a reading assignment due, based on the Sleep and cold article. And I asked them to read the media multitasking paper along with short articles describing the research.

### Breakdown

| Part | Topic | Description | Duration |
| ---- | ---------------- | ------------------------------- | ---------- |
| 0.1 | **Orientation** |  | 0 min |
| 0.2 | **QOD**|Do you think opened-ended questions are better than multiple choice? | 0 min |
| 0.3 | **Mindfulness** | | 1 min |
| | | **Begin Class** |
| 1 | **Discussion** | What did you think about the Media multitasking paper? Pair and talk | 3 min |
|  |  | Start the slides and be sure to pause and let students pair and share | 25 min |
|  |  | Discuss the media reports of the research, compare them. | 5 min |
| 2 | **Lecture** | Ch. 3 slides | 30 min |
| 3 | **Active Learning** | Thought questions | 10 min |
| 4 | **Quiz** | At tables, turn in and leave when finished | 10 min|
| 5 | **Wrap-up**| There are labs tomorrow, be sure you attend YOUR session | 0 min |
| | | **See you next time!** |







